[mysqld]
basedir=C:/Users/Emilio Coding IA/Desktop/sistema pos completo/build/mariadb-runtime
datadir=C:/ProgramData/NovaPOS/MariaDB/data
port=3306
bind-address=0.0.0.0
plugin-dir=C:/Users/Emilio Coding IA/Desktop/sistema pos completo/build/mariadb-runtime/lib/plugin
log-error=C:/ProgramData/NovaPOS/MariaDB/logs/mariadb.err
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
skip-name-resolve

[client]
port=3306
plugin-dir=C:/Users/Emilio Coding IA/Desktop/sistema pos completo/build/mariadb-runtime/lib/plugin
